### ISSUE TITLE
Is syncing continuous or manual? 

### ISSUE THREAD

**Issue by foundinblank** [stitchdata/google-sheets-integration#13]
Am unclear on the [Sync with Stitch](https://github.com/stitchdata/google-sheets-integration#syncing-data) menu item. Do I only have to click on this once and it'll sync automatically from now on, or do I need to manually kick off a sync each time?

**Comment by AliSig** [comment]
Same question as above^

**Comment by foundinblank** [comment]
The answer is "manual." Read more: https://discourse.getdbt.com/t/pulling-in-slow-changing-manually-entered-data/340/6?u=adamstone
